### ISSUE TITLE
fatal error: WiFiGeneric.h: No such file or directory

### ISSUE THREAD

**Issue by firepower9966** [rpsubc8/ESP32TinyZXSpectrum#1]
I enable kempston mouse and 6 bit color in gbConfig.h

 #define use_lib_mouse_kempston
 #define use_lib_sound_ay8912
 //#define use_lib_resample_speaker
 #define use_lib_redirect_tapes_speaker
 //#define use_lib_vga8colors
 #define use_lib_use_bright 

i get fatal error when build. FabGL 0.9.0 and FabGL 1.0.0 both give error  using platformio.ini "lib_deps = fdivitto/FabGL@^0.9.0"

.pio\libdeps\lolin32\FabGL\src\network\ICMP.cpp:26:25: fatal error: WiFiGeneric.h: No such file or directory

Fixed it by adding #include "WifiGeneric.h" to z80emu.cpp

**Comment by rpsubc8** [comment]
Thank you for the correction.
The project for PLATFORM I left it prepared to use only the minimum version of the bitluni vga libraries that are included, while I didn't leave anything prepared for the FABGL libraries.
For FABGL (mouse and sound) I left it prepared only for the Arduino IDE, so you have to download the libraries from the handler, and in principle it compiles without having to add anything.
In next uploads I will see if I introduce fabgl in PLAFORMIO, or I just leave it for the Arduino IDE as it is now.
