### ISSUE TITLE
Audio in 128K?

### ISSUE THREAD

**Issue by vitasam** [rpsubc8/ESP32TinyZXSpectrum#2]
Hello,
great project! 
I managed to build it with VSCode+Platformio - it works with my TTGOVGA32 v.1.4. 
(Although I was not able to build it with Arduino IDE "out of the box" - some files are missed, I did not spend time to investigate it).

I have few questions: 
1. There is no any sound from audio output in 128K audio demo - should it work?
2. Is there a way to load and run games from .txz files?

**Comment by rpsubc8** [comment]
Thank you very much for the tests.
In VSCode+Platformio, all the libraries are included, both for video (bitluni) and audio and mouse (fabgl). In Arduino IDE, only the video (bitluni) libraries are adapted, while for audio and mouse (fabgl) you have to install them from the package manager. Maybe that's the problem with the Arduino IDE, or maybe you have to enable some option like Partition Scheme (Huge app), if there are many files. I need more information on the problem you are getting.
The 128K Audio demo is ready to output audio, but you have to enable in the gbConfig.h file the option use_lib_sound_ay8912 (uncomment the line, remove the //), and compile it. This option makes use of the fabgl library oscillators to output audio through the DAC on pin 25.
I have not added the tzx format yet. I have only added the tap format, but to read a BASIC block, intercepting the ROM routine of the tape. To do this, the option use_lib_tape_rom_intercept must be activated in the gbConfig.h file. When we select from the OSD menu a tape that contains a BASIC program, when we give the load command, it will load it.
I am adapting a routine from other emulators, like fuse, to read complete tapes, as well as tzx, but I can't give concrete dates of when I will have it ready.

**Comment by vitasam** [comment]
Thanks for the info, I will try to re-build with an audio support.
Regarding TAP/TZX files - it will be great to have it support it, so one can enjoy the [best](https://worldofspectrum.org/archive/software/games/exolon-hewson-consultants-ltd) of ZX world :)

**Comment by rpsubc8** [comment]
I have corrected the compilation problem in Arduino IDE, which had the wrong path of the configuration file gbConfig. If you update, it should work.

**Comment by vitasam** [comment]
Thanks! Now it works from Arduino IDE. Also 128K audio demos work now.
